with-expecter: true
resolve-type-alias: False
quiet: False
issue-845-fix: True
disable-version-string: True

filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True

packages:
    github.com/Tbits007/url-shortener/internal/http-server/handlers/url/save:
        interfaces:
            URLSaver:
